Log interactions to MySQL
StampyAI/stampy-chat pull request #87
Opened 2023-08-24 14:53 UTC by mruwnik

* Adds MySQL support
* Logs interactions to the database

2023-08-24 15:08 UTC, mruwnik commented on api/src/stampy_chat/logging.py
> +                # session_id=session_id,
this isn't handled by the frontend yet, so isn't passed in

2023-08-24 15:08 UTC, mruwnik commented on local_db.sh
> +#!/usr/bin/env bash
a helper script to set up the database locally as a docker container. This is the same as for the ARD, but the container has a different name

2023-08-27 02:58 UTC, FraserLee commented on api/src/stampy_chat/db/models.py
> +    session_id: Mapped[str] = mapped_column(UUID(), default=uuid.uuid4)
good choice

2023-08-27 03:00 UTC, FraserLee commented
Good work setting the PR branch of dependent PRs as the target of the next in the chain. Github has awful support for dependent PRs, but I personally really like this workflow \:)

2023-08-27 03:03 UTC, FraserLee commented on api/src/stampy_chat/chat.py
> -def talk_to_robot(index, query: str, mode: str, history: List[Dict[str, str]], k: int = STANDARD_K, log: Callable = logger.info):
Ah I'm seeing you caught this here. Might be better to do these changes on #86 and then merge from `log-queries` up into `mysql-logs`.

2023-08-27 03:05 UTC, FraserLee requested changes

2023-08-27 03:05 UTC, FraserLee commented on api/src/stampy_chat/db/models.py
> +    interaction_no: Mapped[int] = mapped_column(Integer)
Can you turn this into a comment in the file?

2023-08-27 03:05 UTC, FraserLee commented on api/src/stampy_chat/get_blocks.py
again, if possible, unrelated changes should be their own PRs.

2023-08-27 03:05 UTC, FraserLee commented on readme.md
Needs *a lot* more documentation on how to setup and test in a dev environment.

2023-09-01 21:02 UTC, mruwnik commented
moved to other PRs, so closing this one

2023-09-01 21:02 UTC, closed without merging